to_solve([[d, c, g, a], [c, a, d, g, b, f, e], [g, e, c, b, a], [c, b, f, d, e], [e, d, a], [c, d, b, e, a], [g, b, a, d, f, e], [f, e, g, c, b, a], [b, e, d, g, c, a], [d, a]], [[b, g, e, f, d, a, c], [b, d, a, c, e], [a, d], [a, g, c, d]]).
to_solve([[f, e], [e, c, f], [f, d, b, a, g, e, c], [d, c, g, f, a, b], [d, e, f, b, c, a], [e, f, b, c, g, a], [d, a, c, e, g], [c, f, d, e, a], [b, f, e, d], [f, d, b, c, a]], [[a, e, f, d, c], [f, b, d, e], [a, b, d, e, f, c], [d, c, g, a, e]]).
to_solve([[f, b, g], [c, g, a, f, e], [b, f], [b, f, d, c], [e, b, d, c, a, g], [f, g, c, d, b, a], [g, b, d, e, c, a, f], [b, c, f, a, g], [b, a, d, g, c], [g, d, e, f, a, b]], [[b, f, g], [b, f], [b, f], [b, d, g, e, c, a]]).
to_solve([[b, g, e, d, f], [g, e, c, a, b, d], [c, d], [c, a, d, b, g, f], [a, g, c, b, e], [a, e, d, c, g, b, f], [e, c, g, b, d], [e, c, d, a], [a, g, f, e, c, b], [g, c, d]], [[b, d, a, c, f, g, e], [c, d], [c, a, d, e], [d, c, a, e]]).
to_solve([[c, e, d, a, b, f], [g, c, f, a, b], [c, a, d], [a, b, e, g, c, d], [f, c, b, e, d, a, g], [a, e, d, b, f], [g, b, e, d, a, f], [d, c], [e, c, d, f], [b, d, f, c, a]], [[c, a, d], [d, c], [d, c], [b, e, d, a, c, f, g]]).
to_solve([[e, d], [g, f, d, c, b, a, e], [a, c, b, d, f, g], [e, c, g, d], [c, d, f, e, a, g], [f, b, d, a, g, e], [d, f, c, a, e], [f, b, a, e, c], [e, d, a], [g, d, a, c, f]], [[d, a, e], [f, a, d, g, b, c], [e, c, g, d], [a, e, d, c, g, f]]).
to_solve([[d, g, b], [g, b], [d, f, a, e, b], [b, e, a, d, g], [c, d, a, e, g], [b, g, d, f, a, e], [b, a, f, g], [c, d, g, f, e, b], [a, e, b, f, c, d], [g, c, a, e, b, d, f]], [[a, e, f, c, b, d], [b, g, a, f], [a, f, g, b], [d, g, b]]).
to_solve([[f, d, a, b, c], [e, f], [c, f, a, e, d], [d, a, e, b, g, c], [f, g, e, b, d, a], [f, d, e], [d, c, e, a, g], [g, f, c, e], [c, b, g, f, d, e, a], [e, a, c, f, g, d]], [[a, d, c, e, g], [e, d, b, c, a, g, f], [e, d, f], [f, e]]).
to_solve([[d, a, g, e, b, f], [b, d, c], [b, c], [a, f, e, c, d], [d, a, c, e, b], [c, g, b, e], [d, a, b, c, e, g], [e, d, b, a, g], [d, f, c, a, g, b], [c, e, f, g, b, a, d]], [[d, b, c], [d, a, b, g, e], [a, b, d, g, c, e], [c, e, g, b]]).
to_solve([[d, f, g, e, b], [e, b, g, f, c], [d, c, a, b, e, f], [g, c, a, b], [b, c], [g, a, e, c, b, f], [c, d, f, e, g, a], [c, g, f, a, e], [b, c, e], [e, f, a, b, d, c, g]], [[c, g, f, a, e], [c, b], [g, c, d, e, b, a, f], [e, f, g, c, a]]).
to_solve([[a, f, c], [g, c, d, e, a, b], [g, d, b, f, a, c], [b, c, e, a, f, d], [b, e, c, a, d], [e, b, a, f], [f, a], [f, a, e, c, d], [g, f, a, d, e, b, c], [c, e, d, f, g]], [[c, g, d, f, e], [a, f, c], [a, c, f], [a, f]]).
to_solve([[d, c, g, b, a], [g, f, a, b, d, c], [e, d, g, b, f, a], [g, f, d, a, b], [b, d, c], [a, c, f, e, g, d, b], [b, c], [a, d, g, e, c], [b, g, f, c], [e, a, d, b, c, f]], [[f, d, a, e, g, b, c], [g, f, b, c], [b, d, c], [c, b]]).
to_solve([[a, d, g], [g, b, f, a, c], [a, c, d, f, b, g, e], [f, e, d, c, a], [c, d, g, f, a], [e, c, a, f, b, g], [a, e, g, b, f, d], [g, d], [c, b, d, g], [g, d, f, a, b, c]], [[b, d, f, g, a, c], [f, c, a, b, e, d, g], [a, g, d], [d, f, b, g, c, e, a]]).
to_solve([[f, d, c, g, b, a], [b, f, c], [c, f, a, d, b], [a, e, b, f, d], [a, c, g, b], [c, a, f, g, d], [f, g, d, c, e, b], [g, c, d, a, e, f], [c, a, g, b, e, d, f], [c, b]], [[b, c, a, g], [d, f, e, b, a], [a, g, b, c], [c, b, a, g]]).
to_solve([[g, e, d, a, f], [a, f, b, c, d, e, g], [e, c, g, a, d, b], [c, b, g, a, f, e], [d, c], [e, f, g, c, d], [d, c, e], [c, g, e, f, b], [c, g, d, b, e, f], [f, b, d, c]], [[b, c, g, e, f], [e, f, g, a, b, c], [d, c], [d, e, g, f, c, b]]).
to_solve([[a, b, d, g, c, f], [a, b, e, f, c], [f, d], [g, f, b, a, c, d, e], [g, c, e, d, b], [g, e, d, f], [c, f, d], [e, d, g, a, c, b], [f, e, g, b, c, d], [f, e, b, d, c]], [[c, e, f, d, a, b, g], [b, a, c, e, f], [f, c, d], [f, e, g, d]]).
to_solve([[f, a, e, g, b, c], [d, f, c, a, b, g], [a, f, g, b, e, d], [d, a, e, b, c], [e, g], [g, f, e, c], [a, f, c, b, g], [a, c, e, d, g, b, f], [e, c, g, b, a], [e, g, b]], [[e, g], [e, g], [b, g, a, d, f, c, e], [b, a, e, g, c]]).
to_solve([[e, d, f, b, a], [b, c, g, a, f, d], [e, d, b, g], [b, g, a, d, f], [e, d], [a, d, e, f, c, g], [g, f, e, b, d, a], [e, c, a, g, d, b, f], [e, f, a, b, c], [e, d, f]], [[d, a, e, g, b, f], [e, b, f, a, d], [c, e, a, f, b], [b, g, d, e]]).
to_solve([[f, c, e, b, a, d], [g, c, f, e, b, d], [a, g, c, d, b, f, e], [d, a, e, f, g, c], [g, d, a, b, f], [c, d, g], [b, e, c, g], [c, f, b, d, e], [f, g, b, c, d], [g, c]], [[c, g], [g, a, f, d, b, c, e], [c, b, d, g, f], [g, f, d, a, b]]).
to_solve([[b, f, c, e, a, d, g], [d, f, e], [g, e, a, d, b], [c, g, f, d], [e, d, f, g, b], [g, d, c, f, e, b], [c, a, b, g, e, f], [f, d], [c, f, g, b, e], [a, e, f, d, c, b]], [[c, g, d, f], [d, f], [a, g, b, d, e], [e, d, g, c, b, f]]).
to_solve([[a, g, e], [b, e, c, f, a, d], [c, f, b, e, g], [e, a, g, d, f, b], [d, f, e, c, g, a, b], [a, c, f, e, g], [e, f, d, a, c], [d, g, a, c], [c, g, a, d, f, e], [g, a]], [[g, f, e, c, a], [a, e, c, g, f, d], [e, a, g, c, f], [f, a, d, c, b, e, g]]).
to_solve([[g, a, b, e, d], [e, f, a, b, g, d], [e, g, a, f, c, d], [a, f, g, e, c, b, d], [a, d, e, f, b], [b, a, f, c, d], [g, b, e, d, a, c], [f, e, b, g], [f, e], [f, e, a]], [[g, f, e, b], [f, e], [b, a, d, g, e], [a, d, f, e, b]]).
to_solve([[e, d, c, g, f], [a, d, g, f], [a, f, g, c, b, e], [e, c, f, b, g, d], [d, c, e, g, a, f], [a, f], [d, a, c, b, e], [e, f, a, c, d], [a, f, c], [c, a, f, d, g, b, e]], [[f, a], [e, d, b, c, g, f], [d, c, g, f, e], [a, d, e, c, b]]).
to_solve([[d, g, a, b, f, c], [d, b, a, g, c], [c, b, d, g, e, a], [g, e], [d, e, c, a, g, f], [g, e, b, a], [g, c, b, f, d, a, e], [d, g, e], [b, d, g, e, c], [e, c, f, d, b]], [[a, b, c, g, d], [d, c, a, b, g], [d, g, b, a, f, c], [e, g]]).
to_solve([[g, a, d, f, e], [f, g, b, c, d, e], [a, f, g, d, b, c], [e, c, f, b], [c, f], [e, d, g, c, b], [d, e, f, c, g], [d, b, a, g, c, e], [f, c, b, g, d, e, a], [d, f, c]], [[d, b, g, e, c], [a, d, g, b, c, f], [d, c, e, f, g], [f, c]]).
to_solve([[g, f, e, d, a], [a, b, f], [b, g, f, d], [e, b, d, f, g, c, a], [g, a, e, f, b], [d, e, b, a, f, g], [f, b, e, a, c, d], [f, b], [g, c, d, a, f, e], [a, e, b, g, c]], [[g, d, f, b], [f, d, b, c, a, e, g], [g, d, f, b], [b, f]]).
to_solve([[e, a], [e, a, b], [c, e, a, b, g], [d, e, a, c], [d, a, e, b, c, g], [g, e, d, a, f, b], [b, d, a, g, c, f, e], [e, f, d, c, b, g], [c, g, b, f, a], [b, g, c, e, d]], [[g, f, a, e, b, d, c], [a, c, d, e], [c, a, e, d], [d, b, a, f, g, e]]).
to_solve([[e, g], [c, a, f, d, e], [g, d, f, e], [a, e, d, c, g, f], [f, a, g, b, c, d, e], [b, a, e, f, c, g], [a, d, c, g, b], [e, a, g], [c, f, d, e, a, b], [a, c, d, g, e]], [[b, f, d, c, a, e, g], [e, g], [e, g, a], [g, e]]).
to_solve([[e, d], [d, c, g, b, e], [f, b, c, a, d, g], [g, d, e], [b, c, a, g, d], [g, d, b, a, c, e], [d, b, e, a], [e, a, c, f, d, g], [f, e, a, c, b, d, g], [b, f, g, e, c]], [[g, e, d], [g, b, a, d, f, e, c], [c, d, e, a, f, g, b], [a, c, b, f, g, e, d]]).
to_solve([[g, c, b, d, f, e], [b, e, a, d], [d, a], [e, b, f, d, c], [a, d, e, b, c, f], [e, c, f, d, b, g, a], [d, c, f, b, a, g], [c, a, d], [d, e, c, a, f], [e, a, f, c, g]], [[e, g, d, c, b, f], [d, a, c], [b, c, g, f, d, e], [c, b, g, e, d, f, a]]).
to_solve([[c, g, a, f, e, d, b], [c, a, b, f, d, g], [d, e, a, g, f], [g, a, c, d, e, b], [e, b], [c, b, d, a, f], [b, d, a, f, e], [a, e, b], [b, c, e, f], [a, f, c, e, b, d]], [[b, e, c, f], [d, a, g, e, f], [b, e, f, c], [d, b, f, a, e]]).
to_solve([[a, d], [g, d, e, b, c, f], [d, a, b, c, g, f], [a, f, b, c, e], [d, b, g, a], [e, c, d, a, f, g], [a, d, c], [b, g, c, f, d], [c, a, d, b, f], [d, e, c, a, g, b, f]], [[d, a], [f, d, c, a, b], [c, d, a], [d, a, c]]).
to_solve([[c, e, b, f, d], [a, b], [c, e, b, a, d, g], [f, a, d, g, e, c], [a, g, d, b], [e, a, b], [c, a, g, e, d], [b, c, d, e, a], [f, e, g, b, a, c], [d, b, c, f, e, g, a]], [[b, a, e], [e, b, d, f, c], [e, b, g, c, a, d], [b, d, e, f, c, g, a]]).
to_solve([[a, d, e, g, c, f, b], [e, d, f, b, a], [a, b, d, g, e, f], [a, f, c, b, d], [d, b, a, g, c], [e, d, f, c], [e, f, b, d, c, a], [f, c], [f, a, c], [a, b, g, c, e, f]], [[b, d, e, a, f], [g, e, b, f, a, d, c], [f, a, e, c, g, b], [d, a, b, f, e]]).
to_solve([[b, g, f, e, c, d, a], [d, b, c, e, a, f], [g, a, b, e, d, f], [g, d, f], [f, g], [c, g, e, d, a], [b, g, e, f], [c, f, d, g, a, b], [f, d, a, g, e], [a, e, b, f, d]], [[b, a, d, f, e], [e, g, b, f], [e, f, g, b], [g, f, e, c, b, d, a]]).
to_solve([[d, e, a, f, g, b], [b, c, d, g, e], [d, f], [d, a, c, f], [g, f, a, c, b], [c, f, a, g, b, e], [b, a, g, d, c, f], [g, c, b, d, f], [e, c, a, b, g, d, f], [d, f, g]], [[f, b, d, g, c, a], [d, g, f], [d, f, g], [g, f, a, d, e, c, b]]).
to_solve([[d, b, c, a, f, e], [g, e, b, c, f, a, d], [f, a, g, c, d, b], [g, e, c, f, b], [c, g, d, e, b], [a, d, e, g], [c, b, e, a, g, d], [c, d, a, e, b], [c, d, g], [g, d]], [[e, d, f, a, c, b], [g, e, c, b, f], [d, c, g], [d, c, b, a, f, e]]).
to_solve([[f, a, c, d, e, g], [c, b, e, f, g, d], [b, e, d], [c, d, e, b, f, a], [e, g, f, b], [g, f, e, c, d], [e, c, d, b, g, f, a], [b, e], [d, g, b, a, c], [e, b, c, g, d]], [[e, b, f, g], [c, e, b, d, a, f], [c, a, b, e, g, f, d], [g, f, e, c, d]]).
to_solve([[b, a, c, f, d, g], [c, d, b, a, e, g, f], [c, a, e, d], [f, c, b, g, e], [c, g, e, b, a, d], [g, b, a, f, d, e], [c, g, b, d, a], [e, g, c, a, b], [a, e], [a, e, b]], [[g, a, c, e, b], [e, d, f, a, b, g], [c, d, f, b, a, g], [c, f, b, e, g]]).
to_solve([[a, d, f, g, c], [f, g, e, c, a, d], [g, d, a, b, f], [a, c, b, g], [g, d, a, f, c, b], [f, c, d, a, b, e, g], [g, d, b], [g, b], [d, g, e, c, b, f], [e, b, f, a, d]], [[a, b, c, d, g, f, e], [g, c, b, a], [f, d, a, b, e], [g, b]]).
to_solve([[d, f, b, c], [d, f], [a, d, e, c, g], [d, e, f], [d, f, e, c, a], [c, a, f, b, g, e], [e, a, f, d, b, g], [b, d, c, g, a, f, e], [c, b, e, f, d, a], [b, f, c, e, a]], [[a, d, e, f, c], [d, f], [e, f, c, d, a], [a, e, c, g, b, f, d]]).
to_solve([[a, e, g], [g, e, f, c, a, b, d], [a, g, d, c, b], [d, f, g, c, b, a], [e, g, b, d, f, a], [b, f, e, c, a], [e, d, c, g], [g, e], [b, a, c, g, e], [c, e, g, d, b, a]], [[g, a, e], [c, d, b, g, a], [g, e, a], [e, g]]).
to_solve([[c, d, e, g, b], [b, f, g, c], [b, g, d], [e, c, d, a, g], [d, g, b, f, a, e], [e, d, c, f, b], [b, g], [d, a, f, b, c, e], [e, d, f, c, b, a, g], [d, c, f, g, e, b]], [[f, c, g, b], [e, f, g, c, d, b], [b, c, d, e, g], [g, b]]).
to_solve([[g, d, e, f], [d, b, a, f, c, e, g], [c, d, b, e, a, g], [a, d, e], [g, f, c, a, e], [f, d, a, b, c], [d, e], [f, e, d, a, c], [e, f, c, b, g, a], [e, c, g, d, a, f]], [[a, e, d], [d, e, a], [g, f, a, c, e], [a, g, e, b, d, c]]).
to_solve([[g, d, e, a, c], [a, b], [b, g, a], [b, a, e, f], [e, a, c, g, b], [g, b, c, a, f, e], [b, c, g, e, f], [b, e, d, c, f, g], [d, g, f, b, c, a], [g, a, c, e, d, b, f]], [[g, a, b], [e, b, c, g, f, d], [f, g, d, e, a, b, c], [a, b]]).
to_solve([[e, f, a], [e, b, a, g, d], [d, e, b, a, g, f], [g, e, f, b], [f, e], [e, b, d, a, g, c], [g, f, d, e, a], [e, g, f, c, b, d, a], [d, g, a, c, f], [d, b, f, c, a, e]], [[a, f, g, d, c], [g, f, b, e], [e, f, a], [b, d, e, g, c, a]]).
to_solve([[d, a, e, f, g, b, c], [a, f, e, c, g, b], [f, d], [c, f, b, d, g], [f, d, g], [a, b, c, f, g], [c, g, e, b, d], [a, b, g, e, f, d], [f, c, a, d, b, g], [d, c, f, a]], [[d, g, f], [d, f], [a, f, c, d], [d, f, g]]).
to_solve([[a, g, f], [d, g, f, c, e, a], [e, c, f, g], [b, d, f, g, a, e, c], [f, g], [d, f, a, e, c, b], [a, b, g, c, f, d], [d, f, g, e, a], [b, a, g, e, d], [a, c, d, f, e]], [[f, g], [e, f, c, g], [f, a, g], [d, a, f, e, g]]).
to_solve([[a, e, d, c, f, g], [g, f, c, a, e], [c, d, e, b, g], [g, a, b], [a, b], [a, b, e, g, c], [b, f, a, e], [a, e, g, c, f, d, b], [b, f, a, e, c, g], [d, b, f, c, g, a]], [[d, b, g, f, a, c], [d, b, g, c, e], [c, e, a, g, f, d, b], [b, a]]).
to_solve([[b, d], [a, f, e, g, c, b], [b, e, d, c, f, a], [a, d, b], [d, g, e, c, a, b, f], [f, d, e, b], [b, f, e, c, a], [a, c, d, b, f], [f, c, a, d, g], [b, c, a, g, d, e]], [[e, b, c, g, f, d, a], [d, b], [e, c, d, a, b, f], [d, a, e, b, g, c]]).
to_solve([[b, d, f], [f, b], [d, b, e, f, c, g, a], [e, d, f, g, c], [f, b, g, a], [e, d, a, b, g], [f, a, b, e, c, d], [e, d, f, b, a, g], [g, e, f, b, d], [a, c, b, d, e, g]], [[c, e, d, g, f], [e, d, b, a, c, g, f], [f, b, a, g], [g, d, b, e, a]]).
to_solve([[b, f, c], [c, f, e, a, b, d], [g, f, a, e, b], [c, g, b, f, e], [f, c, d, g, e], [e, f, c, a, g, d], [b, d, c, g], [b, g, a, d, f, c, e], [b, c], [d, c, f, g, b, e]], [[c, d, g, b, f, e], [g, c, b, d], [c, b], [c, f, b]]).
to_solve([[g, f, b, d, e], [f, d, g, e, c], [e, f, a, g, c, d], [e, b, c, g], [e, b, d], [e, b], [g, d, f, b, a], [e, c, b, f, g, d], [d, e, a, b, g, c, f], [b, e, c, d, f, a]], [[g, c, d, f, b, e, a], [g, e, c, b], [f, e, b, c, g, d], [g, b, c, e]]).
to_solve([[a, c, f], [c, b, g, f, a, d], [g, a, b, e, c, d], [b, c, f, d], [b, d, a, g, f, c, e], [a, e, b, g, f], [f, a, g, c, b], [c, a, d, g, e, f], [d, a, g, b, c], [c, f]], [[d, b, c, f], [a, f, g, c, e, d, b], [e, d, c, f, a, g], [c, f, b, d]]).
to_solve([[f, b, c, a, g], [e, c], [g, a, c, f, e, b], [e, f, g, c], [e, c, b], [g, d, f, a, e, b, c], [a, e, b, d, f], [g, b, e, c, a, d], [d, a, c, f, b, g], [c, a, f, e, b]], [[c, e], [c, g, f, a, b], [c, g, d, f, b, a], [c, b, e]]).
to_solve([[a, b, d, c, g, f, e], [g, f, a, d, c, e], [f, c, g, b, e], [f, g, a, d, b, c], [g, c, b], [g, b], [d, e, b, g], [g, d, e, c, f], [b, c, e, a, f], [b, c, d, g, f, e]], [[g, b], [d, g, e, c, f, b], [g, a, e, f, c, d], [b, c, g]]).
to_solve([[f, d, b, c, a], [a, d, b, f, e], [d, a, b, f, g, c], [e, b, c, d, a, f], [e, f, a, g, b], [d, c, e, f, g, a], [d, e], [b, e, c, d], [d, a, e], [b, a, f, c, e, d, g]], [[c, e, d, a, b, g, f], [d, e], [d, e], [e, d]]).
to_solve([[g, e], [b, c, g, f, a], [e, a, c, d, g, b, f], [a, e, g, c], [e, f, g], [c, a, g, f, b, d], [f, g, c, b, e], [d, b, f, a, e, g], [a, e, c, g, b, f], [b, c, e, d, f]], [[e, c, g, a], [e, c, g, a], [g, f, e], [d, e, b, f, a, c, g]]).
to_solve([[g, e, d, a], [g, f, a, e, b], [a, g, c, d, e, b, f], [a, g, c, f, b], [c, g, f, d, b, e], [e, b, c, a, d, f], [g, f, e], [f, b, d, e, a, g], [e, f, d, b, a], [g, e]], [[d, g, e, a], [e, g, a, d], [e, g], [a, e, g, d]]).
to_solve([[b, g, f, e, c, d], [c, d, e, g, b], [e, c, g, d, b, a], [b, a, g, c, e], [e, a, g], [d, c, f, e, g, a, b], [d, f, c, e, a, g], [a, e], [c, b, a, g, f], [b, d, a, e]], [[f, d, b, e, c, g], [a, b, c, f, g], [g, b, c, f, a], [a, e]]).
to_solve([[a, d, f, b, c], [f, d, b, a, e, g], [b, c, e], [b, c, a, e, g, d], [g, b, d, c, f, e, a], [a, d, c, e, b], [e, c], [d, c, e, g, b, f], [a, c, e, g], [d, a, e, g, b]], [[c, e], [d, g, b, a, e, f, c], [b, d, c, a, e], [f, g, c, d, b, a, e]]).
to_solve([[f, a, e, d, b], [b, e, f], [f, d, c, b, a, e], [c, f, b, d], [e, c, g, a, d, f, b], [b, f], [g, a, b, e, f, c], [f, e, g, a, d], [b, c, d, g, a, e], [e, d, b, c, a]], [[b, f], [c, e, b, d, f, a, g], [e, b, d, f, c, a], [f, b]]).
to_solve([[b, a, d, f, g], [a, c, d, f, g, b], [d, b, g, a, e], [f, e, g, b, d, c], [a, g, f, e], [a, f, c, e, d, g, b], [a, e, b, c, d], [e, g], [e, d, g], [e, g, f, a, d, b]], [[e, a, f, g], [e, g], [g, d, c, b, a, f], [c, d, a, b, f, g]]).
to_solve([[g, a, c, d, f], [c, e, g, f, d], [a, c, d, e, g, f], [d, b, g, f, e, c], [a, d], [f, b, g, a, c], [d, g, f, a, e, c, b], [d, g, e, a], [b, a, f, c, e, d], [a, f, d]], [[a, g, b, d, e, f, c], [a, g, d, e], [a, d], [d, a]]).
to_solve([[c, f, b, d, g], [f, c, a, d, g, b], [f, b, g], [g, c, a, b], [f, b, c, d, e], [g, b], [d, e, g, b, f, a], [d, c, f, a, g], [e, d, g, c, a, f], [c, d, b, g, f, a, e]], [[f, d, b, c, a, e, g], [b, a, g, c], [b, d, e, g, a, f], [c, f, d, b, g]]).
to_solve([[f, g, e, a, b], [a, b, e, g, c], [a, f, d, e, c, b], [c, d, g, b, e, f], [f, g], [g, f, d, a], [b, e, a, d, f], [g, d, e, f, a, b], [b, d, a, e, f, g, c], [g, e, f]], [[f, e, g], [f, g], [b, g, f, c, d, e], [d, f, g, a]]).
to_solve([[f, g, c, a, b], [b, e, c, d, f, g], [d, f, e, c], [d, c, a, b, e, g], [d, a, e, b, g, f], [g, b, f, c, d], [f, d], [d, g, e, b, c], [e, b, c, f, d, g, a], [d, f, g]], [[e, a, d, f, b, g], [e, d, f, c], [e, c, d, g, b], [f, e, c, d]]).
to_solve([[g, f, c, d], [f, b, a, e, g], [d, f], [b, e, g, d, f], [f, d, b], [g, c, e, d, b], [a, d, b, g, e, c], [f, d, c, b, g, e], [c, b, f, d, e, a], [a, c, f, g, b, e, d]], [[g, b, c, a, e, d], [c, b, g, e, d], [d, e, g, f, c, b, a], [d, f, b]]).
to_solve([[a, d, g, f, b], [e, a, g, f], [b, f, a, d, e], [d, g, b, a, e, f], [b, c, d, g, f], [d, g, a], [b, c, f, d, a, e], [a, g], [g, e, c, a, d, b], [e, d, b, g, f, c, a]], [[g, a], [a, b, g, e, f, d], [g, a], [g, e, a, f]]).
to_solve([[c, d, g], [b, f, c, d, e, g], [d, a, g, b, c], [d, c], [e, a, c, g, b], [c, e, a, f, d, b, g], [a, b, g, f, d], [g, e, f, a, b, d], [c, f, d, b, a, g], [c, a, d, f]], [[b, d, a, c, g], [g, c, d], [a, c, d, f], [d, c, f, a]]).
to_solve([[c, a, e, f, d], [d, g], [e, f, b, g, c, a], [g, f, a, e, b, d, c], [b, d, e, a, c, g], [a, c, e, g, d], [d, e, b, g], [f, d, c, b, a, g], [c, b, e, a, g], [a, d, g]], [[f, d, c, e, a], [g, d], [d, e, g, b], [d, a, g]]).
to_solve([[g, f, d], [c, f, b, e, a, g], [d, a, b, f, e], [d, g, c, e], [d, b, f, g, e], [f, b, g, c, e], [c, f, a, g, d, b], [b, c, g, e, f, d], [b, g, e, c, a, d, f], [g, d]], [[g, d], [e, c, g, d], [d, f, b, e, a], [c, f, e, d, a, g, b]]).
to_solve([[c, g, a, b, e], [d, b, e, f, g, a], [e, g, d, f, b, a, c], [b, d, c, f, e], [a, c, g, d], [e, b, c, d, g], [g, b, a, e, c, d], [g, d, b], [d, g], [e, c, g, a, f, b]], [[d, a, g, c], [b, a, d, f, e, g, c], [d, g, a, c], [g, d, b]]).
to_solve([[e, b, f, c], [c, f], [c, b, d, a, f], [b, d, a, c, e, f], [a, c, d, b, g], [d, b, e, a, f], [d, b, e, c, a, g, f], [g, a, d, f, c, e], [a, b, g, e, d, f], [c, f, a]], [[c, a, f], [d, c, f, e, b, a], [d, e, b, f, c, a], [e, c, g, d, f, a]]).
to_solve([[g, c], [c, a, d, e, b], [c, b, f, e, d, g], [e, g, a, b, f], [e, b, a, c, g], [b, a, d, g, c, e], [g, f, b, a, d, e, c], [e, c, g], [d, e, f, b, a, c], [g, c, a, d]], [[c, b, g, d, a, e], [c, a, g, d], [e, c, a, g, b, d, f], [c, g, e, d, a, f, b]]).
to_solve([[e, a, d, g, b], [c, g, d, e, a, f, b], [d, f], [a, e, f, d, g], [e, b, c, a, f, d], [c, d, g, b, e, a], [d, a, g, f, e, b], [a, c, f, e, g], [d, f, a], [b, d, f, g]], [[a, g, c, e, f], [b, f, a, g, e, d, c], [g, a, c, f, e], [f, d]]).
to_solve([[c, b, a, f, e, g], [g, e, d, c, f], [f, d, g, e, c, b], [f, c], [c, f, g], [g, e, b, d, f], [b, g, f, e, d, a], [b, c, d, f], [c, a, g, e, d], [b, c, e, f, d, g, a]], [[c, b, d, f], [f, e, c, d, g], [b, g, e, d, f, a], [b, c, a, e, f, g]]).
to_solve([[b, a, f, c, g], [b, a], [f, a, d, b, c, g], [d, a, c, b], [f, a, b], [b, a, f, d, g, e], [b, e, c, g, f], [f, d, c, g, a], [g, a, f, d, b, e, c], [e, f, c, g, d, a]], [[a, f, b], [g, f, a, b, c, d], [b, g, f, c, a], [b, a]]).
to_solve([[d, f, b, g, a, e], [e, g, b, c], [c, f, a, d, b, e], [d, b, e, a, g, c], [e, c], [a, c, e], [e, c, g, a, f, b, d], [e, d, g, b, a], [a, f, c, g, d], [a, d, e, g, c]], [[d, g, e, f, b, a], [d, f, c, g, a], [a, e, c, b, d, f], [e, b, g, c]]).
to_solve([[c, a, e, g], [f, d, b, c, g], [d, e, c, b, f, a], [d, b, e, f, a, g], [g, b, a, d, c, f, e], [g, e, f], [g, e, f, a, c, d], [c, f, e, g, d], [g, e], [a, e, f, d, c]], [[e, d, g, a, c, f], [f, d, e, g, c], [c, f, g, e, d], [e, g, f]]).
to_solve([[f, a, d], [f, e, d, b, g], [d, a, g, b, c], [d, a, f, b, c, g], [g, e, b, a, d, c], [a, f, c, b], [d, g, a, f, c, e], [d, a, f, g, b], [f, a], [f, d, c, e, b, g, a]], [[b, g, a, f, d], [f, a, b, c], [f, c, b, g, a, e, d], [e, d, a, g, b, c]]).
to_solve([[f, e, b, d, c], [f, g, d, e], [f, g, e, c, b, d], [c, e, g], [a, e, f, c, g, b], [g, e], [b, c, a, d, g], [d, b, e, g, c], [f, a, e, b, c, d], [g, d, f, b, a, c, e]], [[d, c, g, a, f, e, b], [b, c, f, d, g, e], [d, c, f, e, a, b], [c, g, e]]).
to_solve([[e, d, g, f, a, c], [b, f, a, g, c, d], [a, g, e, b], [b, e, d, a, f], [e, a], [f, g, a, b, d], [g, a, e, b, d, f, c], [f, b, e, c, d], [a, e, f], [g, e, f, a, b, d]], [[a, e], [g, c, f, e, d, b, a], [a, e], [f, a, e]]).
to_solve([[a, d, g, b, f, e], [f, c, b, a, d], [f, b, g, d, e, c], [b, e], [e, f, a, d, g], [a, d, f, b, e], [e, d, g, a, c, f], [e, b, f], [d, e, b, c, a, g, f], [e, g, b, a]], [[g, e, a, b], [a, e, f, d, b], [c, d, a, f, b], [e, b]]).
to_solve([[e, b, g, f, a], [a, f, b, c, d], [c, e, d, a, g, b, f], [a, e, b, d, f, c], [f, b, g, a, d], [g, b, d, f, a, c], [g, d], [d, e, f, c, g, b], [a, c, g, d], [g, d, f]], [[g, d], [d, g, f], [d, f, g], [g, d]]).
to_solve([[f, a, c, d, e, b], [e, g, a, b], [e, b, d, g, a, c], [e, c, d, a, b], [c, a, d, g, e], [e, g], [b, d, a, g, f, c, e], [g, c, f, b, d, e], [g, d, e], [a, c, d, g, f]], [[e, f, a, b, c, d], [e, d, g, c, f, b], [d, g, e], [b, g, e, a]]).
to_solve([[c, d, b, a, g, e], [b, g, d, e, f, a, c], [g, a, c, f], [d, a, g, e, c], [f, e, a, d, g, c], [e, c, f, d, a], [b, d, c, e, f], [f, a], [a, f, e], [b, f, e, g, a, d]], [[f, a], [b, g, c, d, e, a], [e, a, f], [c, f, g, a, d, e]]).
to_solve([[e, b, a, c], [d, f, e, g, b], [d, c, b], [b, d, c, f, e, a], [c, b, f, g, d, a], [e, c, a, d, f], [g, e, c, d, b, a, f], [c, f, e, d, b], [d, a, e, c, f, g], [b, c]], [[g, d, e, f, b], [g, f, c, a, d, b, e], [f, a, c, d, b, g], [a, e, g, c, d, b, f]]).
to_solve([[c, f, b, e, a, d], [c, b, d, a, g, e, f], [e, g, d, c], [b, d, c], [b, f, e, g, c], [d, c, b, g, f], [c, d], [g, a, b, e, f, c], [e, b, f, d, g, c], [b, d, a, f, g]], [[f, d, c, b, g], [b, c, g, e, d, a, f], [b, c, d], [e, f, b, g, c]]).
to_solve([[c, f, e, b, g], [b, g, c, a], [f, b, g, d, a, e], [g, e, f, c, d], [c, e, f, b, a], [d, b, e, a, f, c], [g, b, e], [b, g], [a, f, e, g, b, c], [g, b, a, f, d, e, c]], [[b, g], [b, g], [e, c, b, f, a], [a, b, c, g]]).
to_solve([[a, c, g, f, e, d], [c, b, e, a, f], [d, g, b, e], [g, a, b, e, c, d, f], [g, b, f, d, a, e], [f, d, e, a, b], [a, d, f, c, g, b], [a, b, d], [b, d], [e, f, g, d, a]], [[d, e, f, a, b], [b, d, c, g, a, f], [d, g, b, e], [d, b, f, g, e, a]]).
to_solve([[a, b, f, d, c], [c, d, a, b, e, f], [d, b, g, f, a, c], [f, b, c, g], [g, e, d, a, c], [b, g], [e, b, g, d, f, a], [g, a, b], [g, b, d, c, a], [f, a, g, b, e, d, c]], [[g, b], [c, b, g, f], [f, d, c, b, e, a], [a, b, g]]).
to_solve([[e, c, d, a, f, g], [a, b, c, g], [d, g, b], [g, b], [b, d, e, f, g, c], [b, a, g, c, d, e], [d, e, g, a, c], [a, d, f, e, b], [e, g, d, a, b], [c, g, b, d, e, f, a]], [[b, a, g, e, d], [e, a, d, b, f], [b, g], [g, f, e, c, d, a]]).
to_solve([[c, b, g, e], [e, b], [e, g, f, a, b], [e, f, d, a, c, g], [b, f, a, g, e, c], [a, g, d, b, f], [c, e, d, a, b, f], [g, b, a, d, e, c, f], [a, b, e], [c, e, f, a, g]], [[a, f, b, c, e, g, d], [g, e, b, c], [a, b, e], [a, b, e]]).
to_solve([[f, b, g, a, e, c], [e, g], [b, g, d, f, e, a], [g, c, b, f, d, a], [b, d, c, e, f, g, a], [f, b, d, c, e], [c, a, e, g], [a, b, g, f, c], [g, e, f], [e, c, g, b, f]], [[c, a, f, b, g], [a, c, b, e, g, f, d], [e, g], [c, f, a, b, g]]).
to_solve([[c, a, f], [b, a, f, g, d], [b, f, g, e, c], [b, a, e, c], [a, c], [d, g, c, e, a, f], [f, b, a, g, c, e], [b, a, d, f, c, e, g], [e, b, d, c, f, g], [c, g, f, a, b]], [[b, a, g, f, d], [b, a, g, d, f], [c, d, b, a, g, f, e], [c, f, a]]).
to_solve([[e, g, d, a, c], [e, d, b, c, g, f, a], [a, c, b, e, f, d], [b, f, g, e, a], [a, g, f, e, b, d], [a, b, c, e, g], [f, e, b, g, a, c], [b, c], [e, b, c], [b, f, g, c]], [[c, b, e], [b, g, c, f], [c, g, a, e, b], [c, e, g, b, a]]).
to_solve([[f, c], [a, c, b, d, e, f], [f, d, b, a, e], [f, g, e, a, b, d, c], [d, b, c, e, f], [g, e, f, d, b, a], [b, c, f], [e, f, a, c, g, b], [g, c, d, e, b], [c, f, a, d]], [[e, f, d, a, b], [e, a, f, b, d], [c, a, f, d, b, e, g], [f, c]]).
to_solve([[a, e, g, f, c, d, b], [g, f, c, e, a, b], [c, e, g, a, d, b], [g, f, e, d, b], [g, b, a, e, c], [f, a], [b, f, a], [f, c, g, a], [d, c, b, f, e, a], [e, f, g, b, a]], [[b, a, f], [g, c, a, d, b, e, f], [b, f, a], [d, b, g, f, e]]).
to_solve([[g, f, a, c, b, d], [g, c, b, a, f, e, d], [e, d, c, b, f, a], [b, d], [a, c, d, f, g], [a, b, d], [d, a, e, c, f, g], [a, g, b, f, e], [b, a, f, g, d], [b, d, g, c]], [[a, g, c, d, b, f], [b, g, d, c], [c, d, g, b], [b, d, a]]).
to_solve([[f, e, g, d, b], [a, f, d], [b, f, g, d, a, e], [a, e, b, f, d], [g, a, e, c, f, d], [g, d, a, b], [d, a], [b, a, e, c, f], [d, b, g, c, f, e], [d, b, g, a, c, f, e]], [[d, f, b, e, g, a], [a, b, g, d], [d, f, e, c, b, a, g], [g, f, d, e, b]]).
to_solve([[c, f], [d, a, b, c, e], [b, e, d, c, a, f], [f, c, a], [b, e, a, f, c, d, g], [g, d, e, c, a, f], [c, f, b, e, a], [a, f, g, e, b], [d, e, c, g, a, b], [d, c, b, f]], [[e, a, c, f, d, b], [a, c, b, e, f], [c, f, a], [b, d, c, f]]).
to_solve([[a, e, g, c, f, b], [g, a, d, f, e, c], [b, g, f, c, e], [b, f, d, a, e], [f, a, c], [g, a, c, b], [c, a], [a, b, c, g, e, f, d], [e, d, b, c, f, g], [f, e, b, c, a]], [[c, a, g, e, f, b], [f, c, a], [a, c], [f, e, g, b, d, c]]).
to_solve([[d, e], [d, b, f, c, e, g, a], [d, b, e, c, g, a], [d, e, g], [d, c, b, e], [a, f, c, b, g, d], [b, c, g, d, a], [e, f, c, a, d, g], [g, d, a, e, b], [e, b, a, g, f]], [[g, a, e, b, c, d], [g, d, e], [b, c, d, e], [b, c, d, e]]).
to_solve([[d, b, g, a, f], [g, a, e], [c, d, g, b, f, a], [g, a, f, b, c, e, d], [a, c, g, f, d, e], [a, b, e, f], [c, g, d, e, b], [g, d, e, f, b, a], [a, e], [d, g, e, a, b]], [[b, c, d, g, e], [c, f, b, a, e, g, d], [e, b, a, d, g], [f, e, b, a]]).
to_solve([[b, d, e], [d, g, e, a], [d, c, g, b, f], [f, b, d, g, e], [d, e], [d, a, f, g, b, e], [e, f, b, a, g], [b, f, e, a, d, c], [f, e, c, a, b, g], [f, d, b, a, g, c, e]], [[d, e], [d, b, e], [f, e, a, b, d, g, c], [g, d, a, e]]).
to_solve([[a, g, d, e, c], [b, d, g, e, c], [g, e, c, a, f, b, d], [b, c, e, d, f, g], [a, d], [f, g, b, a, c, d], [d, b, a, e], [d, e, g, b, a, c], [c, a, e, g, f], [a, d, g]], [[f, e, c, g, a], [a, d, g], [g, c, d, e, b, f, a], [c, e, f, g, a, d, b]]).
to_solve([[b, c, e, a, d, g], [a, g], [c, a, f, g, b, d, e], [f, e, d, b, g], [g, a, b], [d, b, c, f, a, g], [c, e, a, b, d], [a, g, b, e, d], [g, a, e, c], [b, e, f, c, d, a]], [[g, a], [a, g], [g, a, c, e], [a, g, d, b, c, f]]).
to_solve([[a, e, c, d, b, g], [a, g, b, e, f], [a, b, c], [b, e, c, f, a, g, d], [a, g, f, c, b], [c, a], [c, f, b, d, g], [f, a, d, c], [d, g, c, a, b, f], [b, c, d, g, e, f]], [[c, a], [f, b, d, e, g, c], [d, c, a, f], [g, c, f, a, b]]).
to_solve([[c, e, d, g], [a, g, f, e, d, c, b], [f, e, c, a, g, b], [b, a, e, d, f], [e, b, a, g, d, c], [e, c], [b, e, c], [d, a, g, c, f, b], [e, a, b, c, d], [d, c, a, g, b]], [[b, c, e], [g, d, e, c], [c, d, g, e], [b, a, g, d, c]]).
to_solve([[f, g, d, c, a], [c, g], [c, d, g, b, e, f], [g, d, b, f, a], [c, b, a, g], [f, d, e, a, c], [a, d, f, b, c, g], [c, d, g], [e, b, c, g, d, a, f], [e, a, b, d, g, f]], [[c, d, g], [g, b, a, f, d], [g, c], [c, a, b, d, e, g, f]]).
to_solve([[g, d, b, c], [b, a, c, f, g, e], [d, f, b, e, c, a], [g, c], [g, c, f], [f, e, b, c, d], [g, f, a, d, e], [c, f, e, d, b, a, g], [f, d, g, e, c], [b, d, e, f, c, g]], [[c, g, b, d], [e, d, g, f, a], [c, b, d, g], [a, f, g, e, d]]).
to_solve([[f, e, b], [c, e, f, a, g], [f, d, a, b, c], [e, c, g, b], [g, d, e, a, b, f], [c, f, g, d, a, e], [f, a, c, b, e], [e, b], [b, e, c, a, f, g], [d, g, b, c, f, e, a]], [[e, g, f, d, a, c], [a, c, f, d, e, g], [d, g, e, c, f, b, a], [f, c, d, a, b]]).
to_solve([[f, a, e, d, g, c], [a, e, c, d, b], [a, f, c, b], [d, e, f, g, b, a, c], [b, a, e], [e, a, d, b, c, f], [f, a, b, g, e, d], [f, e, d, c, a], [d, e, g, b, c], [a, b]], [[b, a], [f, a, d, c, e], [g, a, d, e, c, b, f], [b, a]]).
to_solve([[e, d, f, g], [e, g, f, c, d, b], [e, g], [d, f, e, c, b], [g, e, b], [c, b, g, a, f], [d, c, g, a, e, b], [a, c, b, e, d, f], [c, f, b, g, e], [f, a, d, b, c, g, e]], [[g, e], [b, e, f, g, d, c, a], [f, c, e, b, d], [c, f, g, e, b]]).
to_solve([[f, c, a, g, d, b], [e, b, d, c, g, f, a], [f, d, a, e, b, c], [g, a, f, c, e], [g, e, b, c, a, d], [f, a, b], [f, b], [c, a, b, f, g], [b, c, g, d, a], [g, f, d, b]], [[f, b, a], [c, a, e, f, b, d], [f, b], [g, f, c, a, b]]).
to_solve([[c, f, e, g, b, a, d], [g, c, d, a, b, f], [c, d, g, e, b, f], [f, e], [b, g, e, a, c], [g, d, b, e, a, f], [b, g, e, f, a], [e, f, d, a], [g, f, e], [a, g, f, d, b]], [[g, e, b, a, c], [e, f], [a, g, e, b, d, f, c], [e, d, a, f]]).
to_solve([[e, c, b, d, g], [a, e, c], [f, e, b, d, c, a], [b, g, e, c, a, f], [e, a, f, d], [a, g, d, f, c, b], [c, a, d, g, f, b, e], [e, d, a, c, b], [e, a], [b, a, f, d, c]], [[e, f, d, a], [c, a, g, e, f, b], [d, e, f, a], [a, e, c]]).
to_solve([[e, f, a, g, d, b], [c, f, g, b, d, a], [g, f, d, b, c, a, e], [e, d, c, b, f, a], [c, a, d, g, b], [d, g], [d, a, g], [d, g, f, c], [e, b, c, a, g], [b, c, a, d, f]], [[d, g], [c, a, g, d, b], [g, d, a, b, f, c], [d, a, g]]).
to_solve([[d, g, c, f, e, b], [d, f, e, b, g, c, a], [f, b, g, a], [a, f, e, c, d], [g, a, e, c, b], [c, f, b], [b, c, a, f, e], [e, a, c, b, d, g], [f, b], [c, f, g, e, a, b]], [[b, f], [a, e, c, b, g], [g, b, f, a], [d, g, a, c, e, b]]).
to_solve([[d, e], [d, b, c, g, f, a], [f, g, d, a, c, e], [a, c, b, d, g], [a, b, c, e, d], [g, a, e, b, c, d], [g, e, b, d], [f, b, c, a, e], [a, f, b, g, d, c, e], [c, e, d]], [[e, d, c], [g, d, b, e], [b, c, d, a, e], [f, b, a, g, d, e, c]]).
to_solve([[g, f, d, b, c, e], [b, g, d, a], [d, f, c, a, b], [a, b, f, g, c, e], [c, d, f, g, b, e, a], [d, b, f], [d, e, c, a, f], [g, d, c, b, a, f], [b, c, f, g, a], [d, b]], [[b, f, e, d, g, c], [g, c, d, b, a, f], [b, d], [a, g, d, b]]).
to_solve([[b, e, f, a, c, d], [b, c, d, e, g], [g, f, a, d], [b, e, g, f, a], [e, d, f, g, b, a], [d, b, f], [d, e, b, f, g], [c, b, g, a, f, e], [f, d], [f, c, e, b, a, d, g]], [[f, b, e, c, g, a], [d, f, e, g, b, c, a], [f, d], [b, f, g, a, e, d]]).
to_solve([[a, c, g, e, b], [a, d, e, b, f, c, g], [f, e, b, a, d, g], [b, e, a, f, c], [a, e, g, c, b, d], [a, e, f], [g, c, f, e], [a, c, g, b, f, e], [a, c, f, b, d], [e, f]], [[d, b, c, e, f, a, g], [a, f, e], [b, c, e, g, a], [e, a, f]]).
to_solve([[f, c, a, e, g, d], [b, g], [d, b, a, g, f, c], [g, b, c, e], [g, b, e, d, f, c], [e, d, b, c, f, a, g], [b, f, g, e, d], [f, c, e, g, d], [b, d, g], [f, b, a, d, e]], [[d, c, b, a, g, e, f], [a, f, e, c, d, b, g], [e, b, c, d, a, f, g], [g, b]]).
to_solve([[f, b, d, c, g, a], [d, a], [f, d, a, b, c, g, e], [f, a, d], [d, b, a, g], [g, b, d, e, c, f], [g, c, a, f, d], [g, b, c, f, d], [c, d, b, a, f, e], [a, e, c, f, g]], [[a, d], [a, g, d, b], [d, c, f, e, b, g], [g, a, d, b, f, c]]).
to_solve([[d, b], [b, d, g], [g, a, d, f, c], [g, d, f, c, b], [d, b, e, c, f, g], [e, f, d, b], [g, b, e, a, f, c], [e, b, g, f, c], [g, d, c, f, a, e, b], [b, a, c, e, d, g]], [[g, b, d], [f, g, b, d, c], [d, f, g, a, b, c, e], [g, a, d, f, c]]).
to_solve([[b, f, e, a, d, g], [e, a, f, b, c, g], [f, b, a, g, e], [e, d], [e, d, f, g, a, c], [f, e, d], [a, g, c, d, e, b, f], [d, a, b, e], [d, g, c, b, f], [f, d, e, b, g]], [[f, c, g, d, a, e, b], [f, d, e, b, c, g, a], [a, b, f, e, c, g], [f, g, c, e, b, a]]).
to_solve([[c, g, f, d], [e, a, g, d, c], [a, f, g], [a, f, e, g, b, d], [f, a, e, b, c], [c, d, f, e, g, a], [a, b, e, g, c, d], [g, d, e, b, f, a, c], [f, g], [g, a, f, c, e]], [[a, f, g, e, b, d], [g, f, a], [b, e, d, a, g, f], [g, f, d, c]]).
to_solve([[e, f, a, g, d], [f, g, c, b, e, d, a], [b, f, g, a, c], [c, e, g, d], [c, d], [e, d, g, a, f, c], [f, e, d, g, b, a], [b, d, e, c, a, f], [c, d, a], [c, f, g, d, a]], [[d, c], [c, d], [a, e, c, b, f, d], [d, f, a, e, b, c, g]]).
to_solve([[e, d, a, b, f], [e, a, c, d, b], [g, c, d, f, b, a], [f, d, b, a, e, g], [c, a], [g, c, b, f, d, e, a], [c, d, b, e, g], [c, a, d], [d, f, a, c, e, b], [e, c, a, f]], [[c, a], [d, e, b, f, a], [c, f, e, d, a, b], [b, a, e, d, c]]).
to_solve([[e, c, a, f, b, g], [b, d], [a, f, d, b, c, e], [d, e, b], [g, e, d, c, b, f, a], [b, f, a, d], [c, e, g, a, d], [c, g, f, d, b, e], [f, e, b, a, c], [d, b, a, c, e]], [[b, e, d], [b, d, e], [b, d], [e, c, a, d, g]]).
to_solve([[b, a, f, g, d], [a, g, f, b, d, e, c], [d, a, e, g, b, f], [d, g, e, c, b], [c, b, f, g, a, d], [a, d, c, b, f, e], [a, f, e, g], [d, b, f, g, e], [e, b, f], [f, e]], [[d, a, b, f, g, c], [f, b, e, g, d], [f, e], [e, d, c, b, f, a]]).
to_solve([[b, d, e, g, f], [b, d], [c, e, d, f, g], [g, e, c, f, d, a], [f, b, d], [f, b, a, e, g], [c, e, f, b, d, a, g], [a, c, d, f, g, b], [d, b, e, c], [d, b, f, c, g, e]], [[b, d], [b, d], [c, b, a, e, f, d, g], [f, e, g, a, b]]).
to_solve([[d, g, f, c, a, e], [a, g, d], [a, f, b, e, d, g], [e, a, g, b], [d, a, e, b, f], [f, g, e, d, b, a, c], [a, f, b, e, d, c], [d, a, f, g, b], [f, g, b, c, d], [a, g]], [[f, b, e, d, a], [a, e, c, b, f, d], [g, b, f, c, d], [f, b, a, d, e, g]]).
to_solve([[e, c, g, d, f, a], [c, b, g, d, e], [b, d, a, f, e, g, c], [f, g], [e, b, c, f, a, d], [f, b, a, c, e], [f, b, a, g], [e, g, c, b, a, f], [e, f, g], [b, f, g, c, e]], [[g, b, e, f, c, a], [e, c, f, a, g, b], [f, a, g, b], [c, e, g, d, b]]).
to_solve([[a, f, g, e, d, c, b], [f, a, b, c, e], [g, a, e], [e, c, b, a, g], [f, e, d, g, b, a], [e, f, c, a, b, g], [b, d, a, f, c, e], [g, e], [b, c, g, a, d], [c, e, f, g]], [[a, g, e], [g, e, a], [e, g, f, c], [e, g, a]]).
to_solve([[f, a, d, g, b], [f, d, g, e, a, b, c], [b, c, e, f, d, g], [c, d, f, e, b, a], [f, c, d, g, b], [g, b, e, d, c], [e, g, c, f], [c, f], [b, a, e, d, c, g], [d, f, c]], [[d, g, c, b, f], [g, a, f, e, b, c, d], [c, d, f], [b, f, d, a, c, e, g]]).
to_solve([[a, g], [g, e, b, d, c, a], [d, g, b, f, c], [g, e, f, d, c, a, b], [f, g, c, a, b], [e, a, g, f, b, c], [e, c, f, a, b], [e, a, c, b, f, d], [f, a, e, g], [b, g, a]], [[b, g, a], [g, a], [g, a, b], [b, c, f, d, g, a, e]]).
to_solve([[b, d, g, c, e, a], [g, d], [g, e, c, d], [f, c, g, a, d, b], [g, a, d], [e, g, c, b, a], [g, c, b, a, e, f], [e, a, f, d, b], [d, b, a, e, g], [c, f, e, b, g, d, a]], [[d, b, a, c, g, f], [d, c, e, g], [g, d, f, e, c, a, b], [g, d]]).
to_solve([[b, g, d, c, f, e], [b, d, a], [a, d, b, e, c], [e, d, f, a, c, b, g], [a, d], [d, g, c, a], [b, c, e, f, a], [b, e, c, d, g], [d, a, c, e, g, b], [b, a, d, g, e, f]], [[d, a], [a, d, b], [e, g, b, a, f, d, c], [a, d, b]]).
to_solve([[e, b, a, f, d], [f, b, g, c, a, e], [b, e, g, f, a, d, c], [f, c, g, b, e, d], [f, e, a, b, c], [c, g, f, a], [b, d, e, g, a, c], [c, a, b, g, e], [f, c], [e, c, f]], [[c, f, e], [f, g, e, b, a, c], [g, e, d, c, a, f, b], [c, f]]).
to_solve([[g, c, f], [b, a, d, e, c, g, f], [f, g], [b, c, e, f, g, d], [f, b, g, a, c], [a, e, g, b, c], [a, f, g, d], [a, c, b, d, f], [b, c, d, e, a, f], [g, d, f, a, b, c]], [[g, c, f], [a, b, c, f, d, g], [f, g], [c, b, f, a, d]]).
to_solve([[d, b, g, a, c, e], [a, f, c, g, d, b, e], [f, d, c, e], [b, a, e, f, d], [g, b, c, a, f], [a, b, c, d, f], [d, c], [b, d, c], [d, f, c, e, b, a], [e, f, a, g, b, d]], [[d, c], [d, c], [a, c, g, f, b], [c, d]]).
to_solve([[b, d, a, f, e, g, c], [c, b], [b, e, c, g], [b, e, c, a, d, g], [a, b, c], [e, d, b, c, a], [d, f, a, b, g, c], [b, e, a, d, f], [e, c, d, a, f, g], [e, d, g, c, a]], [[d, b, f, c, a, g, e], [e, b, d, a, f], [b, c, a], [b, d, e, a, c]]).
to_solve([[b, f, d, a, c, g], [d, e, g, f], [e, f], [a, b, c, d, e], [f, g, d, a, c], [c, g, a, f, d, e], [a, e, f], [c, f, e, a, d], [a, b, c, g, f, e], [e, d, g, a, f, b, c]], [[e, f, a], [f, c, b, g, a, e], [d, f, e, g], [b, g, a, c, f, d]]).
to_solve([[d, c, a, f, b, g, e], [a, e, d, b, c], [a, b, d, c, g, e], [g, e, b, a, c], [d, a, b, g], [g, b], [c, b, g], [d, a, e, c, b, f], [c, g, f, a, e], [c, g, d, e, b, f]], [[c, b, g], [a, g, d, b], [a, e, f, c, b, d], [a, g, c, e, b]]).
to_solve([[c, f, g, a, e, d], [e, c], [f, c, d, g, b, e], [e, g, d, b, a], [g, d, f, a, c], [b, e, c, a, d, f, g], [d, a, c, g, e], [f, e, a, c], [d, e, c], [b, a, g, f, c, d]], [[c, e], [e, c, d], [e, g, f, a, d, c], [g, d, e, c, a]]).
to_solve([[g, b, d, c, f], [b, a], [e, b, a, c, f, g], [c, a, g, b, d], [f, a, d, b], [g, d, e, c, a], [b, g, f, e, a, d, c], [b, f, d, c, g, a], [c, b, d, e, g, f], [b, g, a]], [[b, a], [d, f, a, b], [a, b], [e, c, b, d, g, f]]).
to_solve([[g, d, c, a, b, f], [b, c, f, d, e], [c, f, d, e, a], [d, c, a], [e, a, f, d, b, c, g], [e, c, a, g, f], [a, d], [g, c, e, f, d, a], [b, a, c, f, e, g], [a, e, g, d]], [[d, c, a], [a, c, d], [a, f, c, g, e, b, d], [e, f, a, c, g]]).
to_solve([[e, b, a, f, c], [e, g, f, b], [e, c, b], [b, e], [g, c, b, f, e, a], [c, f, e, g, a, d], [f, b, c, d, a], [d, b, f, g, a, e, c], [g, c, e, a, f], [c, e, a, b, d, g]], [[a, b, c, d, f], [g, b, e, f], [c, e, b], [c, e, b]]).
to_solve([[d, e, c, b, f], [e, c, d, b, g, a], [a, d, b, c, e], [b, a, c], [g, f, a, c, b, e], [a, b], [a, e, c, g, d], [b, a, d, g], [f, d, b, a, g, c, e], [e, a, f, d, g, c]], [[e, c, a, b, g, f], [b, a], [d, c, a, e, g, b], [c, f, e, b, a, g]]).
to_solve([[f, c, b, d, g, a], [b, e], [g, f, b, c, a], [c, b, e, a, f, d], [b, g, f, e, a], [b, a, g, c, e, f], [a, e, b], [b, c, g, e], [d, e, f, g, c, b, a], [f, a, g, e, d]], [[a, e, b], [b, e, a], [e, b, g, c], [b, e]]).
to_solve([[c, g, b], [a, b, g, c, d, f, e], [a, f, c, b], [b, c], [a, e, d, b, f, g], [g, f, c, b, d], [g, d, e, c, f], [f, d, b, a, g], [f, a, g, b, c, d], [d, g, e, a, b, c]], [[e, f, a, b, g, c, d], [b, d, g, f, c], [d, e, b, c, g, a, f], [e, b, c, f, g, d, a]]).
to_solve([[c, d, a, f, e, g], [b, g, f, e, d, c], [e, d, a, b, c], [b, d, g, e, a], [a, c], [d, e, f, c, b, g, a], [a, b, f, c], [d, a, c], [a, b, e, c, f, d], [b, d, e, c, f]], [[d, b, e, a, g], [a, f, b, c], [a, b, f, c], [c, a]]).
to_solve([[e, g, d], [e, f, g, b, a, c], [c, a, d, g, e, f, b], [e, d, a, f, g], [g, d], [d, f, b, g, e, a], [g, f, b, d], [e, a, b, g, f], [d, a, g, b, c, e], [d, f, c, a, e]], [[f, c, a, e, d], [c, g, b, f, e, a], [d, f, b, g], [b, a, g, e, f, c]]).
to_solve([[a, b, c], [f, g, a, e, c, b], [f, e, d, b, a], [c, e, b, g, d, f, a], [g, a, c, d, f], [a, e, c, f, d, g], [a, b, g, f, c, d], [b, d, g, c], [f, b, c, a, d], [c, b]], [[f, e, c, a, d, g], [c, b, g, d], [d, f, c, e, a, g], [f, c, g, e, a, d]]).
to_solve([[b, d, e, c], [c, g, b], [a, b, e, f, c, g], [b, g, d, c, f], [b, c], [f, g, a, c, b, d, e], [g, d, e, a, f, c], [d, b, e, g, f, c], [f, g, b, d, a], [g, c, e, d, f]], [[a, f, g, d, b], [g, e, c, f, a, d, b], [c, b, e, g, a, f], [c, b]]).
to_solve([[d, f, e, g], [g, c, a, d, e, f], [f, c, e, g, a], [c, b, a, d, e], [f, b, c, a, e, g], [d, e, f, a, c], [f, d], [a, f, d], [a, f, d, e, g, c, b], [a, b, f, c, d, g]], [[f, a, d], [g, a, f, c, e], [b, a, d, e, c], [a, f, d, e, g, c, b]]).
to_solve([[g, d, b, e, a], [e, c], [b, e, c, a, g], [e, b, c], [b, g, e, f, c, d], [e, c, a, d], [c, e, a, b, d, f, g], [g, b, a, f, c], [a, e, g, d, b, c], [d, e, f, g, b, a]], [[b, c, e], [g, d, e, c, f, b], [c, e, d, a], [e, c]]).
to_solve([[e, f, c, b, a, g], [d, c, a, g, f, e], [c, d, e], [e, c, g, f, d], [d, g, e, f, b], [e, f, g, d, a, c, b], [g, b, d, c, a, e], [c, f, g, e, a], [d, a, f, c], [c, d]], [[c, d, f, a], [f, d, a, c], [a, g, f, c, e, b, d], [f, c, d, g, e, a]]).
to_solve([[b, g, a, c, d, e], [f, g, d, c], [b, f, d, c, g, e], [a, f, g, c, d, e, b], [a, c, b, f, e], [g, f], [g, e, f], [e, c, d, g, b], [d, a, b, g, e, f], [c, e, b, f, g]], [[c, f, d, g], [b, f, c, e, a], [a, e, g, d, c, b], [g, e, f]]).
to_solve([[g, f, c, e, a], [a, g, f, d], [d, f, e], [c, d, g, f, e, a], [f, e, d, g, c], [e, g, c, b, a, f], [d, f], [f, d, a, c, b, g, e], [c, e, b, f, a, d], [c, g, b, d, e]], [[e, d, c, f, a, b], [d, f, g, c, a, e], [d, f, g, a], [d, f]]).
to_solve([[e, b, g, a], [e, g, a, c, d, b], [f, d, a, g, b, c], [d, a, b, c, g], [a, e, c], [d, c, g, f, a, e], [b, d, a, e, c], [g, f, b, d, c, a, e], [a, e], [c, e, f, b, d]], [[g, a, e, b], [d, c, a, e, b], [e, a, b, g], [a, c, f, g, e, b, d]]).
to_solve([[a, e, c, f, d, b], [a, g, c, d, b], [f, a, c, g, b], [b, g, e, d], [f, e, c, b, a, d, g], [a, d, b, g, e, c], [b, d], [c, d, g, a, e], [e, a, c, g, d, f], [b, c, d]], [[d, c, b, e, a, f, g], [c, f, e, d, a, b, g], [e, g, d, b], [d, e, g, b]]).
to_solve([[a, e, d, b], [c, f, a, e, b, g], [a, d, e, g, f, b], [g, b, a, f, d], [d, a], [d, e, b, c, a, g, f], [f, a, c, g, e, d], [d, g, c, b, f], [a, f, d], [f, a, e, g, b]], [[a, d], [b, d, a, e], [b, f, e, a, g], [a, e, d, b]]).
to_solve([[b, e, a, g, f, c], [f, c, a, g, d], [f, b, c, g, d], [e, g, d, a, c, b], [e, f, g, a, c, d], [f, e, a, d], [a, c, e, f, d, g, b], [d, g, a, e, c], [a, c, f], [a, f]], [[f, a, g, d, c], [d, f, a, e], [f, a, g, e, c, b], [d, c, g, f, b]]).
to_solve([[b, a, c, d], [g, c, a, e, b], [a, g, d], [b, e, g, d, f], [b, g, d, e, a], [g, d, b, a, e, c], [f, c, a, g, e, b], [c, e, g, d, f, a], [a, f, e, b, d, g, c], [a, d]], [[e, g, d, a, b], [e, d, g, c, f, a], [a, d], [b, g, c, a, f, e, d]]).
to_solve([[d, e, g, a, c, f, b], [d, f, g, a, b], [a, e], [c, g, b, d, e], [e, b, g, a, d], [e, d, a], [c, e, b, d, a, f], [g, a, f, e], [f, a, b, c, g, d], [a, e, g, b, d, f]], [[g, a, f, e], [a, e, b, g, d], [a, e], [b, a, e, g, d]]).
to_solve([[f, d, a, e, b, c, g], [c, e, g, a, d, f], [e, c, a, g], [g, d, c, f, b], [f, e, d, c, a], [d, a, b, f, e, g], [g, e], [a, e, f, b, c, d], [f, g, e], [d, f, c, g, e]], [[e, d, f, c, a], [f, g, e], [e, g, f], [a, g, e, c]]).
to_solve([[d, g, e, b, a, f], [c, a, f, e, b], [g, a], [c, b, f, e, d, a], [f, g, b, a, c], [e, c, a, g, f, b], [b, g, d, c, f], [g, f, a], [c, g, a, e], [f, a, c, g, d, b, e]], [[g, e, c, a, f, b], [c, f, d, g, b], [a, g, f], [g, f, a]]).
to_solve([[f, d, a, g, e, b], [b, f, c, d], [g, d, e, c, a], [e, a, g, f, c, b], [c, b, f, a, e, d], [b, d], [e, b, d], [b, e, a, c, f], [g, b, c, a, f, e, d], [d, b, c, a, e]], [[b, f, e, a, c], [e, c, d, a, g], [f, b, d, c], [f, d, c, b]]).
to_solve([[e, b, f, d], [c, f, e], [c, b, a, e, d], [b, f, c, a, g], [d, f, a, g, b, c, e], [e, f], [d, b, a, e, f, c], [e, c, a, f, b], [e, a, c, g, b, d], [f, a, d, c, e, g]], [[a, b, c, f, e, d], [c, f, b, g, a], [f, e, c], [e, f, c]]).
to_solve([[g, f, e], [g, f, b, a, c], [e, f], [f, d, c, e], [e, d, c, g, a, b], [a, e, g, f, d, c], [b, g, c, d, a, e, f], [d, a, g, e, c], [f, g, c, e, a], [a, f, d, e, b, g]], [[e, b, d, g, a, c], [g, a, c, f, e], [e, f, g], [f, e, g]]).
to_solve([[e, f, d, g, a, c], [a, f, d], [c, a, b, d, e, g], [d, e, f, b], [d, f], [c, g, f, a, b], [b, a, d, e, c], [d, f, c, b, g, e, a], [f, a, b, d, c], [f, b, a, d, e, c]], [[b, a, d, c, e], [e, f, b, d], [d, e, a, c, b], [d, a, f]]).
to_solve([[f, g], [c, f, d, g], [f, g, a], [e, b, a, f, g, c], [c, d, e, b, a, g], [f, b, g, d, c, a, e], [a, e, b, f, d], [f, a, e, g, d], [a, d, g, e, f, c], [d, a, c, e, g]], [[g, f], [f, g, a], [d, e, f, b, a], [g, f]]).
to_solve([[f, e, c, a, b, d], [c, f, a, d, b, g], [c, d, e, b, g, f], [g, f, d, c, b], [b, e, d, c, g], [e, b], [g, d, e, c, a], [b, e, g, f], [c, e, b], [d, f, a, e, c, g, b]], [[e, g, b, f], [c, b, e, f, d, g], [g, c, f, e, a, b, d], [b, g, f, a, e, c, d]]).
to_solve([[g, f], [f, b, e, g, d], [b, c, f, g], [g, c, b, d, e], [d, c, e, f, g, a], [a, e, c, g, b, d], [e, b, c, d, f, g], [b, d, e, g, f, a, c], [d, g, f], [b, e, d, a, f]], [[b, e, d, g, f, c], [f, g], [d, f, g], [e, a, d, b, f, c, g]]).
to_solve([[e, d, f, c, g, a], [e, f, b, c, a, d], [e, b, a], [d, a, b, c, e, g], [b, a], [d, f, b, e, g], [a, g, f, c, d, b, e], [d, f, a, c, e], [e, a, b, f, d], [b, c, f, a]], [[d, g, e, a, c, b], [e, b, d, c, a, g, f], [b, a], [f, a, c, b]]).
to_solve([[c, b, g, e, a, d], [b, e, a, g, f], [d, b, c, g, e], [f, d, c, e, b, a, g], [f, e, c, b, g], [d, b, f, g, c, a], [g, f, c], [e, f, d, c], [d, f, b, e, c, g], [c, f]], [[f, c, g], [d, e, c, g, a, b], [e, f, d, c], [c, f]]).
to_solve([[d, f, b, g, c], [c, a, f], [a, b, e, c, f, g, d], [d, c, e, a], [e, d, a, f, g, b], [c, a], [g, f, d, a, e], [a, c, b, g, e, f], [a, c, f, g, d], [c, a, f, d, e, g]], [[a, e, g, f, c, d, b], [a, d, e, c], [a, g, e, d, c, f], [c, a]]).
to_solve([[f, e], [e, d, b, g, a, c], [f, a, g, c, d, b, e], [e, g, d, b, c], [a, e, d, f, c, g], [e, d, c, f, b], [d, f, e], [c, d, b, f, g, e], [d, c, b, f, a], [e, b, f, g]], [[e, d, b, c, g], [g, a, d, f, e, c], [b, d, a, c, f], [f, d, e]]).
to_solve([[b, a, g], [d, g, e, f, b], [e, a, f, g], [e, a, b, d, g], [b, f, d, c, a, g], [c, e, b, d, f, g], [g, a], [d, g, f, a, b, c, e], [a, g, b, e, d, f], [e, c, b, d, a]], [[g, f, e, a], [b, a, g], [f, d, g, e, a, b], [g, a]]).
to_solve([[d, c, e, g, f], [b, c, f, e, g, a], [b, c, a, d, f, e, g], [g, f, d, e, b], [f, b, g], [c, f, g, a, e, d], [b, e, c, d, g, f], [f, b], [d, b, f, c], [a, g, b, d, e]], [[d, a, g, e, c, f, b], [b, d, f, c], [f, c, g, e, d, a], [b, c, e, a, g, f, d]]).
to_solve([[e, c, g, d, b, a], [c, e, f, d, b, a], [b, a, c, f, g, d], [b, c, d, e, a, g, f], [g, d], [d, e, g, b, c], [g, b, c, f, e], [e, a, d, g], [e, b, a, d, c], [g, d, c]], [[c, e, b, g, d, a], [e, f, c, b, g], [e, d, a, g], [d, g, e, c, b]]).
to_solve([[d, b, e, a, f, c], [c, g, b, d], [c, f, b], [c, f, e, g, d], [c, b], [e, d, f, a, c, g], [b, c, g, f, e], [g, a, b, e, f], [a, d, g, c, e, b, f], [e, d, c, g, b, f]], [[a, b, c, f, d, g, e], [f, b, c], [b, c], [e, f, g, c, b]]).
to_solve([[g, c, e, f, d, a], [f, g, b, a], [f, a], [e, a, f], [b, e, a, d, c], [f, g, b, a, d, e], [g, d, e, b, f, c], [d, f, g, b, e], [f, g, d, c, b, a, e], [f, a, b, e, d]], [[d, e, f, b, g], [d, c, e, f, a, g, b], [a, f], [a, e, b, d, c]]).
to_solve([[f, d, a, e, c], [g, b, f, a, d, c], [b, e, d, g, f, c, a], [e, g, f, d, c], [g, d, c, f, a, e], [g, d], [c, e, b, d, f, a], [e, c, b, g, f], [d, g, f], [g, e, d, a]], [[g, d, f], [c, f, a, d, b, g], [a, c, e, b, f, d], [f, c, a, e, g, d]]).
to_solve([[g, d, b, e, f, a], [e, c, d, f, g], [d, g, e, a, b, c], [g, f, a, b, c, e], [d, b, a, e, g], [c, b, g], [b, c], [c, e, d, g, b], [c, a, b, d], [c, a, d, g, e, f, b]], [[b, c], [c, f, e, d, g], [e, d, f, a, b, g], [g, e, a, b, d]]).
to_solve([[g, b, a], [d, a, f, g, c, b, e], [e, d, a, b, c, g], [f, d, c, a, b, e], [g, c, f, b, e], [a, b, d, e, g, f], [a, e, b, g, f], [f, d, a, b, e], [a, g], [a, f, g, d]], [[b, e, f, c, d, a], [f, e, c, g, a, d, b], [c, g, e, b, a, d], [d, f, g, a]]).
to_solve([[d, a, f, g, e, b], [c, g, d, e], [c, f, a, d, e, g, b], [a, g, f, e, c], [g, c, a, f, b], [c, a, f, e, d], [c, a, g, e, f, d], [g, e], [d, c, a, e, b, f], [e, a, g]], [[f, g, a, c, e], [c, b, e, f, a, d], [e, a, f, c, g], [g, e]]).
to_solve([[d, f, a, b, e, g, c], [c, a, b, e, d, f], [c, b, e], [f, c, e, d], [d, b, e, a, c, g], [e, b, f, d, a], [b, d, f, e, a, g], [e, c], [b, g, c, a, f], [f, c, a, b, e]], [[e, c, b], [f, e, c, d], [c, g, a, e, d, b], [e, b, d, f, a]]).
to_solve([[e, c, f], [f, e, d, a, b, c], [a, f, c, d, g], [f, d, b, c, a, g], [e, f, g, d, c, a, b], [c, b, e, g, a], [f, d, g, e], [f, e], [f, e, a, g, c, d], [f, e, g, a, c]], [[g, a, f, c, e], [c, f, e], [c, d, g, a, b, f], [g, a, c, e, f, d]]).
to_solve([[f, a, b, e, g], [g, d, f], [g, c, f, a, b, e, d], [g, b, a, e, f, c], [d, g], [d, g, a, b, e, f], [d, e, g, b], [g, f, b, a, d], [e, g, d, c, a, f], [a, c, d, f, b]], [[d, e, f, g, c, a], [d, g, f], [c, a, e, f, b, d, g], [b, e, g, f, a]]).
to_solve([[e, a, b, f, g, d], [e, d, f, a, b], [e, b, c, f, a, g], [e, g, d, a, f, b, c], [a, f, d], [e, d, f, g], [f, a, g, e, b], [d, f], [f, g, d, b, c, a], [a, c, e, b, d]], [[g, b, f, e, a], [d, b, f, g, e, a], [a, e, b, f, g, d, c], [d, c, g, f, b, a]]).
to_solve([[c, g], [d, f, e, c, b], [c, e, g, d, b], [d, g, b, c, e, a, f], [d, f, c, g], [b, g, f, d, c, e], [f, b, a, c, e, g], [d, a, b, e, g], [e, g, c], [b, d, f, c, e, a]], [[e, d, g, a, b], [c, g], [e, c, g], [g, e, c]]).
to_solve([[d, b], [d, c, e, a, g], [a, b, e, c, g, f], [b, d, c], [b, f, e, g, c], [b, e, a, c, d, f], [g, b, d, f], [b, c, e, d, g], [b, f, a, c, g, d, e], [e, f, b, c, d, g]], [[g, b, c, e, d], [b, d, a, c, f, g, e], [f, c, g, e, a, b], [f, g, b, d]]).
to_solve([[g, f, e, c, d], [g, d, e, a, c, b], [c, d, f, a, e, b, g], [b, g, f], [d, f, e, b, g], [f, a, b, d], [f, b], [g, d, b, a, e], [g, e, f, a, b, c], [b, d, e, a, g, f]], [[b, a, g, d, e], [b, f, g], [e, g, c, f, d], [b, f]]).
to_solve([[f, c], [d, b, a, g, e, f], [b, f, e, d, c, a, g], [f, c, d, a], [e, b, c, g, d], [f, g, d, e, a], [d, g, e, f, a, c], [e, f, g, a, b, c], [d, e, f, c, g], [f, c, e]], [[a, f, e, g, c, d], [f, a, c, d], [e, a, g, f, b, d, c], [f, c, e]]).
to_solve([[e, a, c, g, b], [g, f, d, a, e, c, b], [e, a, f, b], [e, g, f, d, b, c], [a, c, g, f, b], [f, b], [d, c, e, b, a, g], [f, b, g], [f, d, c, a, g], [a, b, c, f, e, g]], [[b, e, a, f], [e, g, a, b, d, c], [g, b, e, d, c, f], [g, b, f]]).
